/* 
  Sketch generated by the Arduino IoT Cloud Thing "pro"
  https://create.arduino.cc/cloud/things/32bc1301-6a6d-426a-9033-2024c0f59899 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLocation gps;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

//Can't connect to Wi-Fi

// #include "thingProperties.h"
// #define gps 2


// void setup() {
//     // Initialize serial and wait for port to open:
//     pinMode(gps, OUTPUT);
//     Serial.begin(9600);
//     while(!Serial) delay(100);
//     Serial.println("Start Serial Communication");
//     // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
//     delay(1500); 

//     // Defined in thingProperties.h
//     initProperties();

//     // Connect to Arduino IoT Cloud
//     ArduinoCloud.begin(ArduinoIoTPreferredConnection);
    
//     /*
//         The following function allows you to obtain more information
//         related to the state of network and IoT Cloud connection and errors
//         the higher number the more granular information you’ll get.
//         The default is 0 (only errors).
//         Maximum is 4
//     */
//     setDebugMessageLevel(2);
//     ArduinoCloud.printDebugInfo();
// }

// void loop() {
//     //Serial.println("Start arduino cloud update");
//     ArduinoCloud.update();
//     // Your code here 
  
  
// }

// /*
//   Since Gps is READ_WRITE variable, onGpsChange() is
//   executed every time a new value is received from IoT Cloud.
// */
// void onGpsChange()  {
//   // Add your code here to act upon Gps change
//   if(gps)
//   {
//     digitalWrite(gps, HIGH);
//     Serial.println("GPS HIGH");
//   }
//   else
//   {
//     digitalWrite(gps, LOW);
//     Serial.println("GPS LOW");
//   }
    
//   delay(100);
// }




// // -- Second Script -- //




// #include <TinyGPSPlus.h>
// #include <ESP8266WiFi.h>

// TinyGPSPlus gps;

// WiFiServer server(5000);
// WiFiClient client;

// unsigned long lastSend = 0;

// void setup() {
//   Serial.begin(9600);
//   Serial.swap();   // <<< สำคัญมาก

//   WiFi.softAP("ESP8266_GPS", "12345678");
//   server.begin();

//   Serial.println(WiFi.softAPIP());
// }

// void loop() {
//     // รับข้อมูล GPS จาก UART จริง
//     while (Serial.available()) {
//         gps.encode(Serial.read());
//     }

//     if (!client || !client.connected()) {
//         client = server.available();
//     }

//     if (client && client.connected() && millis() - lastSend > 2000) {
//         lastSend = millis();

//         client.print("Chars: ");
//         client.println(gps.charsProcessed());

//         client.print("HDOP: ");
//         client.println(gps.hdop.isValid() ? gps.hdop.value() : -1);

//         client.print("Location valid: ");
//         client.println(gps.location.isValid() ? "YES" : "NO");

//         if (gps.location.isValid()) {
//             client.print("LAT: ");
//             client.println(gps.location.lat(), 6);
//             client.print("LON: ");
//             client.println(gps.location.lng(), 6);
//             client.print("SAT: ");
//             client.println(gps.satellites.value());
//         } else {
//             client.println("GPS not fixed");
//         }

//         client.println();
//     }
// }



// -- Final Script -- //

#include <TinyGPSPlus.h>
#include <ESP8266WiFi.h>
#include "thingProperties.h"

#define gps 2

TinyGPSPlus tinygps;

WiFiServer server(5000);
WiFiClient client;

unsigned long lastSend = 0;

void setup() {
    pinMode(gps, OUTPUT);
    Serial.begin(9600);
    while(!Serial) delay(100);
    Serial.swap();   // <<< สำคัญมาก

    initProperties();

    ArduinoCloud.begin(ArduinoIoTPreferredConnection);

    setDebugMessageLevel(2);
    ArduinoCloud.printDebugInfo();

    WiFi.softAP("ESP8266_GPS", "12345678");
    server.begin();

    Serial.println(WiFi.softAPIP());
}

void loop() {
    ArduinoCloud.update();

    // รับข้อมูล GPS จาก UART จริง
    while (Serial.available()) {
        tinygps.encode(Serial.read());
    }

    if (!client || !client.connected()) {
        client = server.available();
    }

    if (client && client.connected() && millis() - lastSend > 2000) {
        lastSend = millis();

        client.print("Chars: ");
        client.println(tinygps.charsProcessed());

        client.print("HDOP: ");
        client.println(tinygps.hdop.isValid() ? tinygps.hdop.value() : -1);

        client.print("Location valid: ");
        client.println(tinygps.location.isValid() ? "YES" : "NO");

        if (tinygps.location.isValid()) {
            client.print("LAT: ");
            client.println(tinygps.location.lat(), 6);
            client.print("LON: ");
            client.println(tinygps.location.lng(), 6);
            client.print("SAT: ");
            client.println(tinygps.satellites.value());
        } else {
            client.println("GPS not fixed");
        }

         client.println();
    }
}

void onGpsChange()  {
  // Add your code here to act upon Gps change
  if(gps)
  {
    digitalWrite(gps, HIGH);
    Serial.println("GPS HIGH");
  }
  else
  {
    digitalWrite(gps, LOW);
    Serial.println("GPS LOW");
  }
    
  delay(100);
}

